# device
mode: sample  # train sample adapt custom_sample
gpu_ids: [0,1]  # gpu ids
batch_size: 4  # batch size each item denotes one story
num_workers: 16 # number of workers
num_cpu_cores: -1  # number of cpu cores
seed: 0  # random seed
ckpt_dir: ./ckpts # checkpoint directory
run_name: flintstones_pretrain_refined # name for this run

# task
dataset: pororo_unseen # pororo flintstones vistsis vistdii | flintstones_unseen
task: visualization  # continuation visualization

# train
init_lr: 1e-4
warmup_epochs: 5  # warmup epochs
max_epochs: 20  # max epochs
train_model_file:  # model file for resume, none for train from scratch
freeze_clip: True  # whether to freeze clip
freeze_blip: True  # whether to freeze blip
freeze_resnet: False  # whether to freeze resnet
save_freq: 10  # save frequency

# sample
test_model_file: "/home/xiyu/projects/AR-LDM/ckpts/flintstones_pretrain_refined/epoch=19-step=45020.ckpt" #model file for test
calculate_fid: True  # whether to calculate FID scores
scheduler: ddim  # ddim pndm
guidance_scale: 6  # guidance scale
num_inference_steps: 100  # number of inference steps
sample_output_dir: /home/xiyu/projects/AR-LDM/ckpts/output_images/ # output directory
custom_prompts: ./datasets/fs_special_token.txt # custom prompts file, only used for custom_sample
stop_sample_early: # only sample for a few stories
resolution: 256 # resolution for sampling, keep the same as the training resolution

# model config
unet_model:
  tuning:
  low_cpu_mem_usage: False

flintstones_unseen:
  target_chars: ["pebbles", "bamm bamm", "slaghoople"]
  data_dir: ../data/flintstones_data
  target_dir: ../data/flintstones_data/target_chars
  hdf5_file: ../data/flintstones_rare-char_rmeoved.h5
  max_length: 91
  new_tokens: [ "fred", "barney", "wilma", "betty", "dino", "slate"]
  clip_embedding_tokens: 49412
  blip_embedding_tokens: 30525

pororo_unseen:
  target_chars: ['popo', 'pipi', 'whale', 'shark', 'harry', 'tutu', 'alien']
  data_dir: ../data/pororo_png
  target_dir: ../data/pororo_png/target_chars
  hdf5_file: ../data/pororo_char_removed.h5
  max_length: 85
  new_tokens: [ "pororo", "loopy", "eddy", "poby", "tongtong", "crong", "rody", "petty"]
  clip_embedding_tokens: 49416
  blip_embedding_tokens: 30530

pororo:
  hdf5_file: ./data/pororo_char_removed.h5
  max_length: 85
  new_tokens: [ "pororo", "loopy", "eddy", "poby", "tongtong", "crong", "rody", "petty"]
  adapt_tokens:
  clip_embedding_tokens: 49416
  blip_embedding_tokens: 30530

flintstones:
  hdf5_file: ./data/flintstones_rare-char_rmeoved.h5
  max_length: 91
  new_tokens: [ "fred", "barney", "wilma", "betty", "dino", "slate"]
  adapt_tokens:
  clip_embedding_tokens: 49412
  blip_embedding_tokens: 30525

vistsis:
  hdf5_file: /path/to/vist.h5
  max_length: 100
  clip_embedding_tokens: 49408
  blip_embedding_tokens: 30524

vistdii:
  hdf5_file: /path/to/vist.h5
  max_length: 65
  clip_embedding_tokens: 49408
  blip_embedding_tokens: 30524

hydra:
  run:
    dir: .
  output_subdir: null
hydra/job_logging: disabled
hydra/hydra_logging: disabled